version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: attendance_db
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","-u","root","-ppassword"]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 5s

  flask-app:
    build: ./app
    #ports:
    #  - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=attendance_db
    network_mode: host
volumes:
  mysql_data:
    driver: local
